#!/bin/sh

echo "Enter the basic salary : "
read basic

DA=`expr $basic \* 10 / 100`
hra=`expr $basic \* 20 / 100`
gross_salary=`expr $basic + $DA + $hra`
echo "Basic Salary = $basic"
echo "DA = $DA"
echo "hra = $hra"
echo "The gross salary of the employee is $gross_salary" 
